job_name_prefix: dos_pbe
potcar_root: /mnt/dftevn/opt/vasp/pseudo/potpaw_PBE

step1_relax:
  # Add or remove any ASE Vasp keyword here without code edits.
  # Examples: lasph, lcharg, lwave, nelm, algo, ivdw, ispin, magmom, etc.
  vasp_tags:
    xc: PBE
    encut: 520
    kpts: [9, 9, 1]
    ediff: 1e-5
    ismear: 0
    sigma: 0.05
    ibrion: 2
    nsw: 120
    isif: 2
    lwave: false
    lcharg: false

step2_scf:
  vasp_tags:
    kpts: [18, 18, 1]
    lwave: true
    lcharg: true
    nsw: 0
    ibrion: -1
    ismear: -5
    ivdw: 11

step3_dos:
  vasp_tags:
    kpts: [18, 18, 1]
    icharge: 11 # Use charge density from previous SCF step
    lorbit: 11
    nedos: 1000
    nsw: 0
    ibrion: -1
    lwave: false
    lcharg: false
